#!/usr/bin/bash

sudo su


sudo apt-get install python3
sudo apt-get install pip 
pip install pandas


sudo cp -r notlar /usr/bin/notlar
sudo cp -r belgeler /usr/bin/belgeler

echo "Yükleme işlemi tamamlandı. Execute notlar in your terminal"
